# pebble template
pebble:
  suffix: .html
  cache: false

# spring cache redis
spring:
  cache:
    type: redis
  redis:
    host: 레디스 호스트
    port: 포트
    timeout: 1000


  # DB connection
  datasource:
    username: jmlim
    password: password
    url: jdbc:mysql://localhost:3306/employees?&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Seoul

# sql mapper
mybatis:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    jdbc-type-for-null: varchar
    cache-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 6000
  mapper-locations: classpath:/sqlmap/*.xml
  type-aliases-package: io.jmlim.springboot.rediscache
  executor-type: reuse


logging:
  level:
    io.jmlim.springboot.rediscache: debug